name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v2
      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
          host: 3.110.135.10
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd CI-CD
            pm2 stop CI/CD
            npm install
            git pull origin main
            pm2 restart CI/CD