name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
          host: 3.110.135.10
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            whoami
            ls -al